# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PluginZMSP
                                 A QGIS plugin
 Wtyczka umożliwiająca pobieranie zasobów z bazy danych Zintegrowanego Monitoringu Środowiska Przyrodniczego
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-03
        copyright            : (C) 2021 by Sekcja Geoinformacji SKNG
        email                : sekcja.geoinformacji.skng@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PluginZMSP class from file PluginZMSP.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .plugin_zmsp import PluginZMSP
    return PluginZMSP(iface)
